name: SFDC CI Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # full history to support git diff

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Salesforce (JWT)
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sf org login jwt \
            --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ secrets.SF_SERVER_URL }} \
            --alias SFDC_v1 \
            --set-default

      - name: Debug Git Log
        run: |
          echo "Last 5 commits:"
          git log --oneline -5

      - name: Detect Changed Metadata Files
        id: changes
        run: |
          echo "Detecting changes in 'force-app/main/default'..."
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- 'force-app/main/default' | grep -E '\.(cls|trigger|page|component|js|html|xml)$' || true)
          echo "Changed files:"
          echo "$CHANGED_FILES"
          CHANGED_PATHS=$(echo "$CHANGED_FILES" | xargs)
          echo "changed_paths=$CHANGED_PATHS" >> "$GITHUB_OUTPUT"

      - name: Deploy Changed Files
        if: steps.changes.outputs.changed_paths != ''
        run: |
          echo "Deploying only changed files:"
          echo "${{ steps.changes.outputs.changed_paths }}"
          sf project deploy start \
            --source-dir ${{ steps.changes.outputs.changed_paths }} \
            --target-org SFDC_v1 \
            --wait 10 \
            --ignore-conflicts \
            --verbose
