name: SFDC Smoke Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli

      - name: Test SFDX CLI
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sfdx auth:jwt:grant \
            --clientid ${{ secrets.SF_CONSUMER_KEY }} \
            --jwtkeyfile server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instanceurl ${{ secrets.SF_SERVER_URL }} \
            --setalias SFDC_v1
      
      - name: Detect Changed Metadata Files
        id: changes
        run: |
          git fetch origin master
          CHANGED_FILES=$(git diff --name-only origin/master ${{ github.sha }} -- 'force-app/main/default' | grep -E '\.(cls|trigger|page|component|js|html|xml)$' || true)
          echo "$CHANGED_FILES" > changed.txt
          echo "changed_paths=$(cat changed.txt | xargs)" >> $GITHUB_OUTPUT
    
      - name: Deploy Changed Files
        if: steps.changes.outputs.changed_paths != ''
        run: |
          echo "Deploying only changed files:"
          echo "${{ steps.changes.outputs.changed_paths }}"
          sf project deploy start --source-dir ${{ steps.changes.outputs.changed_paths }} --target-org SFDC_v1 --wait 10 --ignore-conflicts --verbose