name: SFDC Smoke Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global

      - name: Test SFDX CLI
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sfdx auth:jwt:grant \
            --clientid ${{ secrets.SF_CONSUMER_KEY }} \
            --jwtkeyfile server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instanceurl ${{ secrets.SF_SERVER_URL }} \
            --setalias ci-org

      - name: Deploy to Org
        run: |
          sfdx force:source:deploy -p force-app\main\default\classes -u SFDC_v1 --checkonly --testlevel RunLocalTests
